name: AdvancedDungeons
authors: [zhehe]
main: zhehe.advanceddungeons.AdvancedDungeons
load: startup
api-version: 1.14
version: 0.9
commands:
  advanceddungeons:
    aliases: [advdun]
    description: Generates AdvancedDungeons everywhere
    usage: /<command> [option] [world-name]
  advanceddungeons_place:
    aliases: [advdun_place]
    description: Generates AdvancedDungeons in the current location
    usage: /<command> [option]
permissions:
  advanceddungeons.enter:
    default: true
    description: gives acced to the enter option
  advanceddungeons.op:
    default: op
    description: gives acced to the apply/unapply/reload options
  advanceddungeons.place:
    default: op
    description: gives acced to the apply/unapply/reload options